(define (problem barman-2-2-1-8-8-28-3)
 (:domain barman)
 (:objects
	shaker1 - shaker
	shot0 shot1 - shot
	dispenser0 dispenser1 dispenser2 dispenser3 dispenser4 dispenser5 dispenser6 dispenser7 - dispenser
	left right - hand
	ingredient0 ingredient1 ingredient2 ingredient3 ingredient4 ingredient5 ingredient6 ingredient7 - ingredient
	cocktail0 cocktail1 cocktail2 cocktail3 cocktail4 cocktail5 cocktail6 cocktail7 cocktail8 cocktail9 cocktail10 cocktail11 cocktail12 cocktail13 cocktail14 cocktail15 cocktail16 cocktail17 cocktail18 cocktail19 cocktail20 cocktail21 cocktail22 cocktail23 cocktail24 cocktail25 cocktail26 cocktail27 - cocktail
	l0 l1 l2 - level)

(:init 
	(ontable shaker1)
	(clean shaker1)
	(empty shaker1)
	(ontable shot0)
	(clean shot0)
	(empty shot0)
	(ontable shot1)
	(clean shot1)
	(empty shot1)
	(dispenses dispenser0 ingredient0)
	(dispenses dispenser1 ingredient1)
	(dispenses dispenser2 ingredient2)
	(dispenses dispenser3 ingredient3)
	(dispenses dispenser4 ingredient4)
	(dispenses dispenser5 ingredient5)
	(dispenses dispenser6 ingredient6)
	(dispenses dispenser7 ingredient7)
	(handempty left)
	(handempty right)
	(shaker-empty-level shaker1 l0)
	(shaker-level shaker1 l0)
	(next l0 l1)
	(next l1 l2)
	(cocktail-part1 cocktail0 ingredient0)
	(cocktail-part2 cocktail0 ingredient2)
	(cocktail-part1 cocktail1 ingredient4)
	(cocktail-part2 cocktail1 ingredient2)
	(cocktail-part1 cocktail2 ingredient2)
	(cocktail-part2 cocktail2 ingredient7)
	(cocktail-part1 cocktail3 ingredient5)
	(cocktail-part2 cocktail3 ingredient0)
	(cocktail-part1 cocktail4 ingredient3)
	(cocktail-part2 cocktail4 ingredient7)
	(cocktail-part1 cocktail5 ingredient7)
	(cocktail-part2 cocktail5 ingredient5)
	(cocktail-part1 cocktail6 ingredient1)
	(cocktail-part2 cocktail6 ingredient5)
	(cocktail-part1 cocktail7 ingredient1)
	(cocktail-part2 cocktail7 ingredient6)
	(cocktail-part1 cocktail8 ingredient1)
	(cocktail-part2 cocktail8 ingredient3)
	(cocktail-part1 cocktail9 ingredient4)
	(cocktail-part2 cocktail9 ingredient6)
	(cocktail-part1 cocktail10 ingredient7)
	(cocktail-part2 cocktail10 ingredient0)
	(cocktail-part1 cocktail11 ingredient2)
	(cocktail-part2 cocktail11 ingredient1)
	(cocktail-part1 cocktail12 ingredient2)
	(cocktail-part2 cocktail12 ingredient7)
	(cocktail-part1 cocktail13 ingredient7)
	(cocktail-part2 cocktail13 ingredient5)
	(cocktail-part1 cocktail14 ingredient5)
	(cocktail-part2 cocktail14 ingredient1)
	(cocktail-part1 cocktail15 ingredient5)
	(cocktail-part2 cocktail15 ingredient2)
	(cocktail-part1 cocktail16 ingredient4)
	(cocktail-part2 cocktail16 ingredient3)
	(cocktail-part1 cocktail17 ingredient7)
	(cocktail-part2 cocktail17 ingredient2)
	(cocktail-part1 cocktail18 ingredient6)
	(cocktail-part2 cocktail18 ingredient1)
	(cocktail-part1 cocktail19 ingredient3)
	(cocktail-part2 cocktail19 ingredient2)
	(cocktail-part1 cocktail20 ingredient0)
	(cocktail-part2 cocktail20 ingredient3)
	(cocktail-part1 cocktail21 ingredient0)
	(cocktail-part2 cocktail21 ingredient3)
	(cocktail-part1 cocktail22 ingredient7)
	(cocktail-part2 cocktail22 ingredient6)
	(cocktail-part1 cocktail23 ingredient4)
	(cocktail-part2 cocktail23 ingredient7)
	(cocktail-part1 cocktail24 ingredient4)
	(cocktail-part2 cocktail24 ingredient6)
	(cocktail-part1 cocktail25 ingredient5)
	(cocktail-part2 cocktail25 ingredient3)
	(cocktail-part1 cocktail26 ingredient4)
	(cocktail-part2 cocktail26 ingredient0)
	(cocktail-part1 cocktail27 ingredient2)
	(cocktail-part2 cocktail27 ingredient1)
)

(:goal
(and
	(contains shot0 cocktail27)
	(contains shot1 cocktail1)
)))